package utilities.baseComponentsForRules3_4_5_6_8_9;

public enum Antipattern {
	RULE_3_ANTIPATTERN,
	RULE_4_ANTIPATTERN,
	RULE_5_ANTIPATTERN,
	RULE_6_ANTIPATTERN,
	RULE_8_ANTIPATTERN,
	RULE_9_ANTIPATTERN,
	NONE_OF_THEM
}
